### ISSUE TITLE
[BUG] Quick start commands are returning an error

### ISSUE THREAD

**Issue by pavelnemirovsky** [microsoft/spacy-ann-linker#6]
### Describe the bug

Testing data seems to be invalid 

### To Reproduce

```
spacy_ann create_index en_core_web_md examples/tutorial/data examples/tutorial/models
Your CPU supports instructions that this binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2
For maximum performance, you can install NMSLIB from sources
pip install --no-binary :all: nmslib

================================= Load Model =================================
⠇ Loading model en_core_web_md✔ Done.

============================ Apply EntityEncoder ============================
⠙ Applying EntityEncoder to descriptions✔ Finished, embeddings created
⠙ Setting kb entities and aliases✔ Done adding entities and aliases to kb

============================== Create ANN Index ==============================

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Traceback (most recent call last):
  File "/usr/src/automation/scripts/experimental-linker/linker/bin/spacy_ann", line 8, in <module>
    sys.exit(main())
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy_ann/cli/__init__.py", line 24, in main
    typer.run(commands[command])
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/typer/main.py", line 855, in run
    app()
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy_ann/cli/create_index.py", line 113, in create_index
    nlp.to_disk(output_dir)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy/language.py", line 927, in to_disk
    util.to_disk(path, serializers, exclude)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy/util.py", line 681, in to_disk
    writer(path / key)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy/language.py", line 925, in <lambda>
    serializers[name] = lambda p, proc=proc: proc.to_disk(p, exclude=["vocab"])
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy_ann/ann_linker.py", line 199, in to_disk
    self.cg.to_disk(path)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy_ann/candidate_generator.py", line 347, in to_disk
    to_disk(path, serializers, {})
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy/util.py", line 681, in to_disk
    writer(path / key)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/spacy_ann/candidate_generator.py", line 336, in <lambda>
    p.with_suffix(".json"), self.short_aliases
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/srsly/_json_api.py", line 74, in write_json
    json_data = json_dumps(data, indent=indent)
  File "/usr/src/automation/scripts/experimental-linker/linker/lib/python3.6/site-packages/srsly/_json_api.py", line 26, in json_dumps
    result = ujson.dumps(data, indent=indent, escape_forward_slashes=False)
TypeError: {'NLP', 'OS', 'ML'} is not JSON serializable
```

**Comment by thejamesmarq** [comment]
Same issue here. Seeing this with a clean virtual environment on python 3.7.9

**Comment by markusneumann** [comment]
Came across the same problem. Installing srsly==2.0.0 (instead of 1.0.5, which gets installed because of the requirements of thinc 7.4.0 and spacy 2.2.4) deals with it, but it does involve some version conflicts, so not an ideal solution.
